variables:
  REGISTRY_HOST: ipe-wim-gitlab.fzi.de:5000
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME
  GIT_STRATEGY: clone

stages:
   - build
   - docker
   - github
   - deploy

build:
  image: node:8.12.0-jessie
  stage: build
  only: 
    - master
    - dev
  script:
    - cd website/
    - echo $PRODUCTION_SCRIPT >> ./static/js/custom.js
    - export NODE_PATH=/cache/node_modules
    - npm cache clean --force
    - npm install --unsafe-perm
    - npm run build
  artifacts:
    paths:
      - website/build/streampipes-docs/**
    expire_in: 1 week

github:
  image: maven:3-jdk-8
  stage: github
  script:
    - git config --global user.email 'zehnder@fzi.de'
    - git config --global user.name 'zehnder'
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - git remote add github https://$GITHUB_TOKEN:x-oauth-basic@github.com/streampipes/streampipes-docs.git
    - git push github $CI_COMMIT_REF_NAME
  only:
    - dev
    - master

nginx:
  image: docker:17.06.0-ce
  stage: docker
  only: 
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
    - docker build --pull --no-cache -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  image: alpine
  stage: deploy
  only: 
    - master
  script:
    - apk add --update --no-cache openssh sshpass
    - sshpass -V
    - export SSHPASS=$BOTY_PWD 
    - sshpass -e ssh -o StrictHostKeyChecking=no $WEBSERVER "export DOCKER_CONFIG=/home/riemer/.docker/;cd /opt/streampipes-docs-new;./deploy.sh"

